### ISSUE TITLE
specified cast is not valid exception

### ISSUE THREAD

**Issue by Suresh6312** [Mimetis/SyncWinRT#10]
while doing synchronisation after  modifying tables in local sqlite database it throws specified cast is not valid in helloworld sample whats the reason and how to set direction in this project helloworld?

**Comment by Mimetis** [comment]
Can you provide me more informations, it could help, thx

Seb

**Comment by Suresh6312** [comment]
New sqlite portable library solved this thanks.

**Comment by Mimetis** [comment]
Great !
