### ISSUE TITLE
Windows Universal App could not load COM component

### ISSUE THREAD

**Issue by cipolleschi** [Mimetis/SyncWinRT#13]
Hi,
I'm developing a Universal App which has to synchronize with an Azure DB.
I developed the WebApp which provides the service by following your tutorial and I have generated the client code thanks to your UI Utility.

When I run the server (locally) with the x86 configuration, the service starts fine.
Then I run the Windows Store App with the x64 Configuration because I have installed the x64 version of the SyncFramework. When the app calls the SynchronizeAsync() method, the toolkit throws the following exception:
System.Runtime.InteropServices.COMException
Retrieving the COM class factory for component with CLSID {EC413D66-6221-4EBB-AC55-4900FB321011} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at Microsoft.Synchronization.SyncIdFormatGroup.get_ProviderSyncServices()
I googled the problem, everybody says to change the target platform to x64 but it is already set to x64.

The toolkit successfully create the db schema but it is not able to synch the data.

What am I missing?

Thank you for your help,
Riccardo.

**Comment by Mimetis** [comment]
Are you sure you have followed the steps to install the Sync Fx ?
Be sure to install both x86 and x64 version.

https://github.com/Mimetis/SyncWinRT/wiki/01-Setup-your-sync-scenario-:-Server-and-Client#visual-studio-and-sync-framework

**Comment by cipolleschi** [comment]
Hi,
 First of all, thanks for the quick reply.

Actually, I solved the issue by manually registering the dll using these commands:
regsvr32.exe “Program Files (x86)\Microsoft SDKs\Microsoft Sync Framework\2.1\Runtime\x86\Synchronization21.dll”

regsvr32.exe “Program Files (x86)\Microsoft SDKs\Microsoft Sync Framework\2.1\Runtime\x64\Synchronization21.dll”

regsvr32.exe “Program Files\Microsoft SDKs\Microsoft Sync Framework\2.1\Runtime\x64\Synchronization21.dll”

But now I have a doubt: when I will distribute the app, do I have to register those dll in every client app?
It will be a real pain in that case...

**Comment by Mimetis** [comment]
No because what you have installed is the "server side"
For the client side, no need to register anything, hopefully :)
