### ISSUE TITLE
Socket error 10013 Access denied

### ISSUE THREAD

**Issue by jawahars16** [Mimetis/SyncWinRT#18]
Whenever I try to do a sync, I am getting this error. I have Windows server 2012 R2 and SQL server 2012. Sync framework 2.1. Trying this in a Windows 8.1 Universal application with Visual Studio 2015.

**Comment by gentledepp** [comment]
Do you have the same problem on another machine as well? For example: Does your app work on your dev machine?
Did you try to give the process running on the windows server admin permissions to see whether it is a permission issue?
What are the authentication settings on your server? (I assume you are using IIS?)
In general: Please provide more details.

**Comment by jawahars16** [comment]
I fixed it. It is Windows 8.1 application. So I just need to enable "Private Internet option" from Package manifest. Anyway, thanks for your help.

**Comment by gentledepp** [comment]
That is interesting. Can you explain it a bit more? I'm curious

**Comment by jawahars16** [comment]
![untitled](https://cloud.githubusercontent.com/assets/14835387/12133838/47531f56-b44f-11e5-8d59-2089a16f2df0.png)

**Comment by gentledepp** [comment]
Aaah.. I see! Thanks. May be of help to me some day :+1:
