### ISSUE TITLE
Request Entity too large (413)

### ISSUE THREAD

**Issue by jawahars16** [Mimetis/SyncWinRT#19]
I am using Sync framework with WinRT application. I have some tables which accept BLOB data. User can upload files from WinRT application and it should sync to server database. For large files, I am getting this **Request entity too large (413) error**.

I know I can set the **maxRecievedMessageSize** in web config. But I cannot create any endpoints. I keep getting error from **ProcessRequestForMessage** method, saying that **When using System.ServiceModel.Channels.Message or types with MessageContractAttribute, the method must not use any other types of parameters**.

http://blogs.msdn.com/b/drnick/archive/2006/11/27/mixing-message-contract-attributes.aspx

Can you please help me in fixing this 413 error?

**Comment by gentledepp** [comment]
Hi!
Sorry for answering soooooo late, but we've overcome this issue by overriding the default "webHttpBinding" as this is used by the syncservice.
So in the web.config, we added this part:

<configuration>
 .....some other config...

  <system.serviceModel>
    <bindings>
      
      <webHttpBinding>
        <binding maxBufferPoolSize="2147483647" maxReceivedMessageSize="2147483647" maxBufferSize="2147483647" transferMode="Streamed">
        </binding>
      </webHttpBinding>
    </bindings>
  </system.serviceModel>

</configuration>


This is absolutely necessary, as I recently found out (by browsing the code of SyncWinRT), that the uploadrequests are not batched at all!
