### ISSUE TITLE
Usage of SyncWinRT with a Java Server?

### ISSUE THREAD

**Issue by Hamza54** [Mimetis/SyncWinRT#23]
Hello folks,
Is there any possibility I can use the package with a restfull server coded in Java instead of .NET WEB API ? or maybe some guidance on how can I use a part of the project and integrate it with a Java server communicating with a UWP .NET client?

thanks

**Comment by Hamza54** [comment]
What if I have a java server that has an Sql Server database hosted on windows? any feedbacks?

**Comment by gentledepp** [comment]
Ok so that should not be a problem then.
The WCF service of sync framework has to be hosted in an IIS website with .NET installed though.
But other that that, sync framework only accesses your database. It is completely application-agnostic.
