### ISSUE TITLE
Usage of SyncClient within a portable project?

### ISSUE THREAD

**Issue by Mmonnddi** [Mimetis/SyncWinRT#24]
Hi,

Sorry to ask my question in this section. Is it possible to use the SyncClient project within a portable project in Xamarin.Forms? If yes, are there any examples of how to do it?
I managed to develop the SVC for the server side, which should do the sync on server, but how to develop the client side (using PCL in Xamarin.Forms)?

Thanks for your feedback

**Comment by vikingau** [comment]
I use it successfully in a shared project. Runs on all platforms.
Sorry no experience with PCL project, since I don't think they are as useful as shared code.
You could possibly use a shared project for the sync part and PCL for your other functions - that works OK...
Geoff

**Comment by Mmonnddi** [comment]
Hmm this seems like quite acceptable for me. But, my experience on Xamarin.Forms unfortunately is quite limited and it is completely focused on PCL.
Is it possible for you to just share a simplistic sample of the sync process in Shared code? I think I will still have to use the server side sync wcf service (as generated by sync framework). It's not a problem, I can read and learn a bit more on the shared code.

It would be very helpful to give me some hints or sample code on how to achieve this.

Thanks Geoff for your reply

**Comment by vikingau** [comment]
Yes, you will still have to use the wcf service.
Basically, the code for the client side is all in the SyncClient.Shared project.
Then you just add the appropriate platform project for SyncClient to the main platform for your project.
If you can't work it out, then post back here.
Using shared code is very simple...

Geoff.

**Comment by Mmonnddi** [comment]
Thanks for the hints Geoff. I will work on it and let you know if I will succeed or encounter any issues

**Comment by gentledepp** [comment]
Hi Mmonnddi!
We are in fact using SyncWinRT in a PCL library. However - SyncWinRT is not PCL compatible, because it uses APIs which are not available in PCL.

What we did was to create an interface for the synccontext in the PCL project and implement it in a Shared Project, so that it compiled against each platform.

So the implementation is in a platform-specific project and is compiled there.
Using IoC it is registered as the interface from the PCL library.

Therefore, in the PCL library, I can resolve that interface and use it - although the implentation behind is platform specific.

Have a look at MvvmCross - especailly the plugin concept to see what I am talking about ;-)

**Comment by Mmonnddi** [comment]
Thanks gentledepp,

Will check it although it seems quite challenging for me with my current experience in Xamarin :)

If I have any issues will let you know

**Comment by gentledepp** [comment]
The following video might help ;-)
[Channel 9: Dependency Injection mit Xamarin Forms](https://www.microsoft.com/germany/techwiese/know-how/video.aspx?id=msdn_de_65740)

**Comment by Mmonnddi** [comment]
Thanks. I actually have experience in MVC so I am familiar with dependency injection in general. The things are getting more clear now after your replies.

**Comment by Mmonnddi** [comment]
Thanks a lot for you help. I managed to make the sync work.

So:
1. create one Shared project, 
2. add the client code generated by the sync tool, 
3. reference it in the platform specific projects where you do the call to the svc service (files generated by the tool again and added as part of the asp.net/wcf project).
4. Create one interface in PCL which has all methods and properties that are implemented at point 3
5. Resolve the interface by using dependency injection (it's quite simple actually, just need to decorate the classes at point 3)
6. Fix any small bugs that will come up - nothing works for the first time I guess. If you change the svc URL, it's enough to just uninstall the project which will remove the DB and then the tables will be provisioned again in SQLite.
