### ISSUE TITLE
different sql server databases and one wcf service for multiple clients

### ISSUE THREAD

**Issue by dkmehta** [Mimetis/SyncWinRT#6]
I have query about SaaS application where different sql server database for multiple client. 
I have create one scope for different sql server databases where database table and structures are same and provisioning. multiple client / devices /Phones contain the same database structure.  I have create wcf service from tools(SyncSvcUtilUI.exe) as per given instruction and hosted on server.

I have set the programmatically connection string as per client send the parameter. I have change in “public static void InitializeService” static method where database connection string is set in config.ServerConnectionString. it will be set as per pass the parameter from client and based on the parameter it will set the sql db connection string and sync the data to client db. 

Its work fine but we are facing issue like when one user start the sync and not finished sync yet and mean while other user call for other database and sync it will connect to first database and sync wrong data. I think its not work because wcf sync service contain the static InitializeService method.

can you please suggest the batter way to do this?

**Comment by Mimetis** [comment]
I'm not sure to understand your problem, but anyway, I think the better solution for you is to make a client database for each client (even on the same machine)
It's a best practice when you are making filtered synchronization.

Let me know if it helped you

Seb

**Comment by Suresh6312** [comment]
Ya I am able to do so making different database per client.

**Comment by Mimetis** [comment]
great :)

**Comment by dkmehta** [comment]
Hi Suresh,
can you please explain how you had done with one wcf service with dynamic connection string and different database per client and server ?

Thanks in Advance

**Comment by dkmehta** [comment]
Hi Mimetis, 
Sql Server 2012 contain 1 Master database which contain connection string of user database (this is dynamic generate by web application). Such User databases are available in same sql server 2012.

I have create one WCF service from tools(SyncSvcUtilUI.exe) as per given instruction and hosted on server. and this service get connection string as per parameter passed by client (from device).

Each client (device) contain same database structure like user database in sql server and sync with  user database as per connection string.

Issue is concurrent request in WCF service to set connection string from master database. Its due to  static method "InitializeService" where database connection string is set in config.ServerConnectionString.

Client1 start sync and config.Serverconnectionstring set with User1 Database. its sync is continue mean while Client2 start sync which is related to User2 database but it did not set User2 database connection string due to config.Serverconnectionstring is already set by Client1 in InitializeService. Due to this Client2 contain wrong data in sync.

we have only one WCF service for sync with parameter.

I hope you can understand this.

Thanks 
Dipesh
